import sys

from PyQt5.QtWidgets import QApplication

from presenter.presenter import Presenter
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(1088, 836)
#         MainWindow.setMouseTracking(False)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
#         self.checkBox.setGeometry(QtCore.QRect(160, 90, 70, 17))
#         self.checkBox.setObjectName("checkBox")
#         self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
#         self.checkBox_2.setGeometry(QtCore.QRect(160, 110, 70, 17))
#         self.checkBox_2.setObjectName("checkBox_2")
#         self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
#         self.checkBox_3.setGeometry(QtCore.QRect(160, 130, 70, 17))
#         self.checkBox_3.setObjectName("checkBox_3")
#         self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
#         self.checkBox_4.setGeometry(QtCore.QRect(160, 150, 70, 17))
#         self.checkBox_4.setObjectName("checkBox_4")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(250, 40, 75, 23))
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(520, 40, 75, 23))
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_3.setGeometry(QtCore.QRect(520, 80, 75, 23))
#         self.pushButton_3.setObjectName("pushButton_3")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(50, 40, 181, 16))
#         self.label.setObjectName("label")
#         self.label_3 = QtWidgets.QLabel(self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(380, 80, 111, 16))
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(380, 40, 111, 16))
#         self.label_4.setObjectName("label_4")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setGeometry(QtCore.QRect(50, 90, 91, 16))
#         self.label_5.setObjectName("label_5")
#         self.label_6 = QtWidgets.QLabel(self.centralwidget)
#         self.label_6.setGeometry(QtCore.QRect(380, 130, 201, 16))
#         self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
#         self.label_6.setMouseTracking(False)
#         self.label_6.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_6.setObjectName("label_6")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(110, 570, 311, 81))
#         self.label_2.setText("")
#         self.label_2.setPixmap(QtGui.QPixmap("./legende.png"))
#         self.label_2.setScaledContents(True)
#         self.label_2.setObjectName("label_2")
#         self.label_7 = QtWidgets.QLabel(self.centralwidget)
#         self.label_7.setGeometry(QtCore.QRect(580, 570, 311, 81))
#         self.label_7.setText("")
#         self.label_7.setPixmap(QtGui.QPixmap("./legende.png"))
#         self.label_7.setScaledContents(True)
#         self.label_7.setObjectName("label_7")
#         self.label_9 = QtWidgets.QLabel(self.centralwidget)
#         self.label_9.setGeometry(QtCore.QRect(160, 260, 231, 31))
#         font = QtGui.QFont()
#         font.setPointSize(20)
#         self.label_9.setFont(font)
#         self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
#         self.label_9.setMouseTracking(False)
#         self.label_9.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_9.setObjectName("label_9")
#         self.label_10 = QtWidgets.QLabel(self.centralwidget)
#         self.label_10.setGeometry(QtCore.QRect(620, 260, 231, 31))
#         font = QtGui.QFont()
#         font.setPointSize(20)
#         self.label_10.setFont(font)
#         self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
#         self.label_10.setMouseTracking(False)
#         self.label_10.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_10.setObjectName("label_10")
#         self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
#         self.graphicsView.setGeometry(QtCore.QRect(135, 290, 281, 221))
#         self.graphicsView.setObjectName("graphicsView")
#         self.line = QtWidgets.QFrame(self.centralwidget)
#         self.line.setGeometry(QtCore.QRect(220, 290, 31, 91))
#         self.line.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line.setObjectName("line")
#         self.line_5 = QtWidgets.QFrame(self.centralwidget)
#         self.line_5.setGeometry(QtCore.QRect(140, 440, 71, 20))
#         self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_5.setObjectName("line_5")
#         self.line_6 = QtWidgets.QFrame(self.centralwidget)
#         self.line_6.setGeometry(QtCore.QRect(140, 350, 71, 20))
#         self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_6.setObjectName("line_6")
#         self.line_7 = QtWidgets.QFrame(self.centralwidget)
#         self.line_7.setGeometry(QtCore.QRect(210, 410, 31, 20))
#         self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_7.setObjectName("line_7")
#         self.line_4 = QtWidgets.QFrame(self.centralwidget)
#         self.line_4.setGeometry(QtCore.QRect(200, 290, 31, 91))
#         self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_4.setObjectName("line_4")
#         self.line_2 = QtWidgets.QFrame(self.centralwidget)
#         self.line_2.setGeometry(QtCore.QRect(200, 420, 31, 91))
#         self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_2.setObjectName("line_2")
#         self.line_3 = QtWidgets.QFrame(self.centralwidget)
#         self.line_3.setGeometry(QtCore.QRect(220, 420, 31, 91))
#         self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_3.setObjectName("line_3")
#         self.line_9 = QtWidgets.QFrame(self.centralwidget)
#         self.line_9.setGeometry(QtCore.QRect(210, 370, 31, 20))
#         self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_9.setObjectName("line_9")
#         self.line_10 = QtWidgets.QFrame(self.centralwidget)
#         self.line_10.setGeometry(QtCore.QRect(600, 350, 71, 20))
#         self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_10.setObjectName("line_10")
#         self.line_11 = QtWidgets.QFrame(self.centralwidget)
#         self.line_11.setGeometry(QtCore.QRect(680, 290, 31, 91))
#         self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_11.setObjectName("line_11")
#         self.line_12 = QtWidgets.QFrame(self.centralwidget)
#         self.line_12.setGeometry(QtCore.QRect(670, 410, 31, 20))
#         self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_12.setObjectName("line_12")
#         self.line_13 = QtWidgets.QFrame(self.centralwidget)
#         self.line_13.setGeometry(QtCore.QRect(660, 290, 31, 91))
#         self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_13.setObjectName("line_13")
#         self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
#         self.graphicsView_2.setGeometry(QtCore.QRect(600, 290, 281, 221))
#         self.graphicsView_2.setObjectName("graphicsView_2")
#         self.line_14 = QtWidgets.QFrame(self.centralwidget)
#         self.line_14.setGeometry(QtCore.QRect(660, 420, 31, 91))
#         self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_14.setObjectName("line_14")
#         self.line_15 = QtWidgets.QFrame(self.centralwidget)
#         self.line_15.setGeometry(QtCore.QRect(670, 370, 31, 20))
#         self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_15.setObjectName("line_15")
#         self.line_16 = QtWidgets.QFrame(self.centralwidget)
#         self.line_16.setGeometry(QtCore.QRect(600, 440, 71, 20))
#         self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_16.setObjectName("line_16")
#         self.line_17 = QtWidgets.QFrame(self.centralwidget)
#         self.line_17.setGeometry(QtCore.QRect(680, 420, 31, 91))
#         self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_17.setObjectName("line_17")
#         self.checkBox.raise_()
#         self.checkBox_2.raise_()
#         self.checkBox_3.raise_()
#         self.checkBox_4.raise_()
#         self.pushButton.raise_()
#         self.pushButton_2.raise_()
#         self.pushButton_3.raise_()
#         self.label.raise_()
#         self.label_3.raise_()
#         self.label_4.raise_()
#         self.label_5.raise_()
#         self.label_6.raise_()
#         self.label_2.raise_()
#         self.label_7.raise_()
#         self.label_9.raise_()
#         self.label_10.raise_()
#         self.graphicsView.raise_()
#         self.line.raise_()
#         self.line_5.raise_()
#         self.line_6.raise_()
#         self.line_7.raise_()
#         self.line_4.raise_()
#         self.line_2.raise_()
#         self.line_3.raise_()
#         self.line_9.raise_()
#         self.graphicsView_2.raise_()
#         self.line_16.raise_()
#         self.line_13.raise_()
#         self.line_17.raise_()
#         self.line_10.raise_()
#         self.line_12.raise_()
#         self.line_14.raise_()
#         self.line_15.raise_()
#         self.line_11.raise_()
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 21))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.checkBox.setText(_translate("MainWindow", "Modifier 1"))
#         self.checkBox_2.setText(_translate("MainWindow", "Modifier 2"))
#         self.checkBox_3.setText(_translate("MainWindow", "Modifier 3"))
#         self.checkBox_4.setText(_translate("MainWindow", "..."))
#         self.pushButton.setText(_translate("MainWindow", "Eingabe"))
#         self.pushButton_2.setText(_translate("MainWindow", "Eingabe"))
#         self.pushButton_3.setText(_translate("MainWindow", "Eingabe"))
#         self.label.setText(_translate("MainWindow", "Select amount of entities (10-200):"))
#         self.label_3.setText(_translate("MainWindow", "Select rate of death:"))
#         self.label_4.setText(_translate("MainWindow", "Select risk of infection: "))
#         self.label_5.setText(_translate("MainWindow", "Select modifier:"))
#         self.label_6.setText(_translate("MainWindow", "..."))
#         self.label_9.setText(_translate("MainWindow", "Without Modifiers"))
#         self.label_10.setText(_translate("MainWindow", "With Modifiers"))
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
if __name__ == '__main__':
    app = QApplication(sys.argv)

    presenter = Presenter()
    presenter.ui.show()

    sys.exit(app.exec_())