# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'endWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 441)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.allHaveDiedLabel = QtWidgets.QLabel(Dialog)
        self.allHaveDiedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.allHaveDiedLabel.setObjectName("allHaveDiedLabel")
        self.verticalLayout_2.addWidget(self.allHaveDiedLabel)
        self.pandemicIsOverLabel = QtWidgets.QLabel(Dialog)
        self.pandemicIsOverLabel.setAutoFillBackground(False)
        self.pandemicIsOverLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pandemicIsOverLabel.setObjectName("pandemicIsOverLabel")
        self.verticalLayout_2.addWidget(self.pandemicIsOverLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.statsLabelEnd = QtWidgets.QLabel(Dialog)
        self.statsLabelEnd.setObjectName("statsLabelEnd")
        self.horizontalLayout_5.addWidget(self.statsLabelEnd)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deathsEndLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deathsEndLabel.setFont(font)
        self.deathsEndLabel.setObjectName("deathsEndLabel")
        self.horizontalLayout_6.addWidget(self.deathsEndLabel)
        self.deathsEndLCD = QtWidgets.QLCDNumber(Dialog)
        self.deathsEndLCD.setObjectName("deathsEndLCD")
        self.horizontalLayout_6.addWidget(self.deathsEndLCD)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.maxInfectedEndLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxInfectedEndLabel.setFont(font)
        self.maxInfectedEndLabel.setObjectName("maxInfectedEndLabel")
        self.horizontalLayout_7.addWidget(self.maxInfectedEndLabel)
        self.maxInfectedEndLCD = QtWidgets.QLCDNumber(Dialog)
        self.maxInfectedEndLCD.setObjectName("maxInfectedEndLCD")
        self.horizontalLayout_7.addWidget(self.maxInfectedEndLCD)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.daysLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.daysLabel.setFont(font)
        self.daysLabel.setObjectName("daysLabel")
        self.horizontalLayout_8.addWidget(self.daysLabel)
        self.daysEndLCD = QtWidgets.QLCDNumber(Dialog)
        self.daysEndLCD.setObjectName("daysEndLCD")
        self.horizontalLayout_8.addWidget(self.daysEndLCD)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.graphicEndWidget = PlotWidget(Dialog)
        self.graphicEndWidget.setObjectName("graphicEndWidget")
        self.verticalLayout_4.addWidget(self.graphicEndWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeEndButton = QtWidgets.QPushButton(Dialog)
        self.closeEndButton.setObjectName("closeEndButton")
        self.horizontalLayout_2.addWidget(self.closeEndButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.allHaveDiedLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#f01e1e;\">Oh no! All particles have died!</span></p></body></html>"))
        self.pandemicIsOverLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#1cd93b;\">The pandemic is over! </span></p></body></html>"))
        self.statsLabelEnd.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Statistics:</span></p></body></html>"))
        self.deathsEndLabel.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic;\">Number of deaths since the beginning of the simulation!</span></p></body></html>"))
        self.deathsEndLabel.setText(_translate("Dialog", "Deaths:"))
        self.maxInfectedEndLabel.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic;\">Highest number of infected particles during the pandemic!</span></p></body></html>"))
        self.maxInfectedEndLabel.setText(_translate("Dialog", "Max. infected:"))
        self.daysLabel.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic;\">Duration of the pandemic in days!</span></p></body></html>"))
        self.daysLabel.setText(_translate("Dialog", "Days:"))
        self.closeEndButton.setText(_translate("Dialog", "Close"))

from pyqtgraph import PlotWidget

